### Site metadata ###

title: Kate Eisen
description: Postdoctoral Researcher, Lund University

github_username: kate-eisen

### Build settings ###

url: "https://kate-eisen.github.io"



header_pages:
  - index.markdown
  - 01_about.markdown
  - 02_research.markdown
  - 03_CV.md

exclude:
  - docs/
  - vendor/
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md

liquid:
  error_mode: strict

strict_front_matter: true

### Theme boilerplate ###

remote_theme: MichaelCurrin/fractal

titles_from_headings:
  strip_title: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
